---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: vim-molecule-centos-7-instance
    image: "centos:centos7"
  - name: vim-molecule-centos-8-instance
    image: "centos:centos8"
  - name: vim-molecule-debian-buster-instance
    image: python:3-buster
  - name: vim-molecule-debian-stretch-instance
    image: python:3-stretch
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  inventory:
    group_vars:
      # Set the role name for testing ing the ansible-runner image
      all:
        ansible_role_name: ansible-role-vim
verifier:
  name: testinfra
